export enum UPDATE_ACTIONS {
    PLACE_AMOUNT_OF_PEOPLE = 'PLACE_AMOUNT_OF_PEOPLE',
    PLACE_MINDSET = 'PLACE_MINDSET',
    PLACE_STATUS = 'PLACE_STATUS',
    PLACE_RECENT_ACTIVITY = 'PLACE_RECENT_ACTIVITY',
}
